import Menu from "@/app/components/Menu/Menu"

export const metadata = {
  title: "Meu Boyler Plate",
  description: "Generated by create next app",

}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
